//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FPLibrary.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FPLibrary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FingerID.
        /// </summary>
        internal static string FingerFieldNameValue {
            get {
                return ResourceManager.GetString("FingerFieldNameValue", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap focus_finger {
            get {
                object obj = ResourceManager.GetObject("focus_finger", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap focus_foot_l {
            get {
                object obj = ResourceManager.GetObject("focus_foot_l", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap focus_foot_r {
            get {
                object obj = ResourceManager.GetObject("focus_foot_r", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap focus_sel_finger {
            get {
                object obj = ResourceManager.GetObject("focus_sel_finger", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap focus_sel_foot_l {
            get {
                object obj = ResourceManager.GetObject("focus_sel_foot_l", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap focus_sel_foot_r {
            get {
                object obj = ResourceManager.GetObject("focus_sel_foot_r", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IndividualID.
        /// </summary>
        internal static string IndividualFieldNameValue {
            get {
                return ResourceManager.GetString("IndividualFieldNameValue", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap LHeel {
            get {
                object obj = ResourceManager.GetObject("LHeel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LIndex {
            get {
                object obj = ResourceManager.GetObject("LIndex", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LLittle {
            get {
                object obj = ResourceManager.GetObject("LLittle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LMiddle {
            get {
                object obj = ResourceManager.GetObject("LMiddle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LRing {
            get {
                object obj = ResourceManager.GetObject("LRing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LThumb {
            get {
                object obj = ResourceManager.GetObject("LThumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap palm {
            get {
                object obj = ResourceManager.GetObject("palm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FPQuality.
        /// </summary>
        internal static string QualityFieldNameValue {
            get {
                return ResourceManager.GetString("QualityFieldNameValue", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap RHeel {
            get {
                object obj = ResourceManager.GetObject("RHeel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RIndex {
            get {
                object obj = ResourceManager.GetObject("RIndex", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RLittle {
            get {
                object obj = ResourceManager.GetObject("RLittle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RMiddle {
            get {
                object obj = ResourceManager.GetObject("RMiddle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RRing {
            get {
                object obj = ResourceManager.GetObject("RRing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RThumb {
            get {
                object obj = ResourceManager.GetObject("RThumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sel_finger {
            get {
                object obj = ResourceManager.GetObject("sel_finger", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sel_foot_l {
            get {
                object obj = ResourceManager.GetObject("sel_foot_l", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sel_foot_r {
            get {
                object obj = ResourceManager.GetObject("sel_foot_r", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FPTemplate.
        /// </summary>
        internal static string TemplateFieldNameValue {
            get {
                return ResourceManager.GetString("TemplateFieldNameValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IndividualFinger.
        /// </summary>
        internal static string TemplateTableValue {
            get {
                return ResourceManager.GetString("TemplateTableValue", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap unsel_finger {
            get {
                object obj = ResourceManager.GetObject("unsel_finger", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap unsel_foot_l {
            get {
                object obj = ResourceManager.GetObject("unsel_foot_l", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap unsel_foot_r {
            get {
                object obj = ResourceManager.GetObject("unsel_foot_r", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap window_options_16 {
            get {
                object obj = ResourceManager.GetObject("window_options_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
